import { useState, useCallback, useEffect, useMemo } from 'react'
import {
    Plus,
    Trash2,
    Calendar,
    Hash,
    Save,
    ChevronDown,
    AlertCircle,
    CheckCircle2,
    Clock,
    DollarSign,
    Percent,
    X,
    FilePlus,
    User,
    FileText,
    Briefcase,
    Box,
    Check,
    HelpCircle
} from 'lucide-react'
import { Link } from 'react-router-dom'
import CustomerSelect from '../customers/CustomerSelect'
import ItemSelect from '../items/ItemSelect'
import { invoiceService } from '../../services/api/invoiceService'
import DuplicateWarningModal from './DuplicateWarningModal'

const InvoiceForm = ({
    initialData,
    onSubmit,
    isSaving,
    customers = [],
    items = [],
    title = 'Invoice',
    backUrl = '/invoices'
}) => {
    const [formData, setFormData] = useState({
        customer: '',
        invoiceNumber: '',
        invoiceDate: new Date().toISOString().split('T')[0],
        dueDate: '',
        status: 'draft',
        items: [{ itemId: '', name: '', quantity: 1, price: 0, taxRate: 0 }],
        notes: '',
        terms: '',
        ...initialData
    })

    const [errors, setErrors] = useState({})
    const [touched, setTouched] = useState({})
    const [showDuplicateWarning, setShowDuplicateWarning] = useState(false)
    const [duplicateInvoices, setDuplicateInvoices] = useState([])
    const [pendingSubmission, setPendingSubmission] = useState(null)

    useEffect(() => {
        if (initialData) {
            setFormData(prev => ({
                ...prev,
                ...initialData,
                items: initialData.items?.length > 0 ? initialData.items.map(item => ({
                    itemId: item.itemId || item.item?._id || item.item || '',
                    name: item.name || '',
                    quantity: item.quantity || 1,
                    price: item.price || item.rate || 0,
                    taxRate: item.taxRate || 0
                })) : [{ itemId: '', name: '', quantity: 1, price: 0, taxRate: 0 }]
            }))
        }
    }, [initialData])

    // Invoice number is now generated by the backend atomically
    // Frontend does not need to generate invoice numbers

    const validateField = (name, value) => {
        let error = ''
        switch (name) {
            case 'customer':
                if (!value) error = 'Customer is required'
                break
            case 'invoiceDate':
                if (!value) error = 'Issue date is required'
                break
            case 'dueDate':
                if (!value) {
                    error = 'Due date is required'
                } else if (formData.invoiceDate && value < formData.invoiceDate) {
                    error = 'Due date cannot be before issue date'
                }
                break
            default:
                break
        }
        setErrors(prev => ({ ...prev, [name]: error }))
        return error
    }

    const handleChange = (e) => {
        const { name, value } = e.target
        setFormData(prev => {
            const next = { ...prev, [name]: value }
            // If invoiceDate changes, re-validate dueDate against the new invoiceDate
            if (name === 'invoiceDate') {
                validateField('dueDate', next.dueDate)
            }
            return next
        })

        // Real-time validation
        validateField(name, value)
    }

    const handleBlur = (field) => {
        setTouched(prev => ({ ...prev, [field]: true }))
    }

    const handleItemChange = (index, field, value) => {
        const newItems = [...formData.items]
        newItems[index][field] = value
        setFormData(prev => ({ ...prev, items: newItems }))

        // Clear global items error if any
        if (errors.items) {
            setErrors(prev => ({ ...prev, items: '' }))
        }

        // Validate individual item fields
        if (field === 'quantity') {
            const errorKey = `item_${index}_quantity`
            if (value <= 0) {
                setErrors(prev => ({ ...prev, [errorKey]: 'Quantity must be > 0' }))
            } else {
                setErrors(prev => ({ ...prev, [errorKey]: '' }))
            }
        }
    }

    const handleItemSelect = (index, itemId) => {
        const selected = items.find(it => it._id === itemId)
        const newItems = [...formData.items]
        newItems[index] = {
            ...newItems[index],
            itemId,
            name: selected?.name || '',
            price: selected?.sellingPrice || 0,
            taxRate: newItems[index].taxRate || 0,
        }
        setFormData(prev => ({ ...prev, items: newItems }))

        // Clear global items error if any
        if (errors.items) {
            setErrors(prev => ({ ...prev, items: '' }))
        }
    }

    const addItem = () => {
        setFormData(prev => ({
            ...prev,
            items: [
                ...prev.items,
                { itemId: '', name: '', quantity: 1, price: 0, taxRate: 0 },
            ],
        }))
    }

    const removeItem = (index) => {
        if (formData.items.length === 1) return
        const newItems = formData.items.filter((_, i) => i !== index)
        setFormData(prev => ({ ...prev, items: newItems }))
    }

    const totals = useMemo(() => {
        const subtotal = formData.items.reduce(
            (sum, item) => sum + (item.quantity || 0) * (item.price || 0),
            0
        )
        const taxAmount = formData.items.reduce(
            (sum, item) =>
                sum + (item.quantity || 0) * (item.price || 0) * ((item.taxRate || 0) / 100),
            0
        )
        return { subtotal, taxAmount, total: subtotal + taxAmount }
    }, [formData.items])

    const validateForm = () => {
        const newErrors = {}

        if (!formData.customer) {
            newErrors.customer = 'Customer is required'
        }

        if (!formData.invoiceDate) {
            newErrors.invoiceDate = 'Issue date is required'
        }

        if (!formData.dueDate) {
            newErrors.dueDate = 'Due date is required'
        } else if (formData.dueDate < formData.invoiceDate) {
            newErrors.dueDate = 'Due date cannot be before issue date'
        }

        if (formData.items.length === 0 || !formData.items.some(item => item.itemId)) {
            newErrors.items = 'At least one item is required'
        }

        formData.items.forEach((item, idx) => {
            if (item.itemId && item.quantity <= 0) {
                newErrors[`item_${idx}_quantity`] = 'Quantity must be greater than 0'
            }
        })

        const allTouched = {
            customer: true,
            invoiceDate: true,
            dueDate: true,
            items: true,
        }
        formData.items.forEach((_, idx) => {
            allTouched[`item_${idx}_quantity`] = true
        })
        setTouched(allTouched)

        setErrors(newErrors)
        return Object.keys(newErrors).length === 0
    }

    const handleSubmit = async (e, forcedStatus) => {
        if (e) e.preventDefault()
        if (!validateForm()) {
            return
        }

        // Use forced status if provided (e.g. from specific buttons), else use current formData status
        const submitStatus = forcedStatus || formData.status

        // Check for duplicates before submitting
        try {
            const duplicateCheckData = {
                customer: formData.customer,
                invoiceDate: formData.invoiceDate,
                dueDate: formData.dueDate,
                total: totals.total
            }

            const response = await invoiceService.checkDuplicate(duplicateCheckData)

            if (response.data?.isDuplicate && response.data?.matchingInvoices?.length > 0) {
                // Show warning modal
                setDuplicateInvoices(response.data.matchingInvoices)
                setShowDuplicateWarning(true)
                setPendingSubmission({ formData: { ...formData, status: submitStatus }, totals })
                return
            }

            // No duplicates, proceed with submission
            onSubmit({ ...formData, status: submitStatus }, totals)
        } catch (error) {
            console.error('Error checking for duplicates:', error)
            // If duplicate check fails, still allow submission
            onSubmit({ ...formData, status: submitStatus }, totals)
        }
    }

    const handleProceedWithDuplicate = () => {
        setShowDuplicateWarning(false)
        if (pendingSubmission) {
            onSubmit(pendingSubmission.formData, pendingSubmission.totals)
            setPendingSubmission(null)
        }
    }

    const handleCancelDuplicate = () => {
        setShowDuplicateWarning(false)
        setDuplicateInvoices([])
        setPendingSubmission(null)
    }

    const getStatusConfig = (status) => {
        const configs = {
            draft: {
                label: 'Draft',
                className: 'bg-gray-100 text-gray-700 dark:bg-slate-700 dark:text-slate-300',
                icon: FilePlus
            },
            sent: {
                label: 'Sent',
                className: 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
                icon: CheckCircle2
            },
            paid: {
                label: 'Paid',
                className: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
                icon: CheckCircle2
            },
            overdue: {
                label: 'Overdue',
                className: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
                icon: AlertCircle
            },
        }
        return configs[status] || configs.draft
    }

    const statusConfig = getStatusConfig(formData.status)
    const StatusIcon = statusConfig.icon

    const isValid = (field) => {
        if (!touched[field]) return true
        return !errors[field]
    }

    const getInputClass = (field) => {
        const base = "w-full pl-10 pr-4 py-2.5 bg-gray-50 dark:bg-slate-800/50 border rounded-xl outline-none transition-all duration-200"
        if (touched[field] && errors[field]) {
            return `${base} border-red-300 dark:border-red-500/50 focus:border-red-500 focus:ring-4 focus:ring-red-500/10`
        }
        return `${base} border-gray-200 dark:border-slate-700 focus:border-primary-500 focus:ring-4 focus:ring-primary-500/10 hover:border-gray-300 dark:hover:border-slate-600`
    }

    return (
        <>
            <form onSubmit={handleSubmit} className="max-w-7xl mx-auto space-y-8 animate-fadeIn">
                {/* Professional Header */}
                <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-gray-100 dark:border-slate-800 overflow-hidden">
                    <div className="px-8 py-6 border-b border-gray-100 dark:border-slate-800 bg-gradient-to-r from-gray-50 to-white dark:from-slate-800/50 dark:to-slate-900">
                        <div className="flex items-start justify-between">
                            <div className="flex items-center gap-4">
                                <div className="p-3 bg-white dark:bg-slate-800 rounded-xl shadow-sm text-primary-600 ring-1 ring-gray-100 dark:ring-slate-700">
                                    <FileText className="w-8 h-8" />
                                </div>
                                <div>
                                    <h1 className="text-2xl font-bold text-gray-900 dark:text-slate-100 mb-1">
                                        {initialData ? 'Edit Invoice' : 'Create New Invoice'}
                                    </h1>
                                    <p className="text-sm text-gray-500 dark:text-slate-400">
                                        {initialData ? 'Update invoice details and items' : 'Fill in the details below to create a new invoice'}
                                    </p>
                                </div>
                            </div>
                            <div className={`flex items-center gap-2 px-4 py-2 rounded-xl ${statusConfig.className} font-medium text-sm ring-1 ring-inset ring-black/5 dark:ring-white/10`}>
                                <StatusIcon className="w-4 h-4" />
                                {statusConfig.label}
                            </div>
                        </div>
                    </div>

                    {/* Main Form Grid */}
                    <div className="p-8">
                        <div className="grid grid-cols-12 gap-8 mb-8">
                            {/* Bill To - Large Left Section */}
                            <div className="col-span-12 lg:col-span-7">
                                <div className="space-y-4">
                                    <label className="flex items-center gap-2 text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wider ml-1">
                                        <User className="w-4 h-4" />
                                        Bill To
                                    </label>
                                    <div className="p-6 bg-gray-50 dark:bg-slate-800/30 rounded-2xl border border-gray-100 dark:border-slate-700/50">
                                        <CustomerSelect
                                            value={formData.customer}
                                            onChange={(id) => {
                                                handleChange({ target: { name: 'customer', value: id } })
                                                setTouched(prev => ({ ...prev, customer: true }))
                                            }}
                                            customers={customers}
                                            required
                                        />
                                        {touched.customer && errors.customer && (
                                            <p className="text-xs text-red-600 dark:text-red-400 flex items-center gap-1 mt-2 animate-in slide-in-from-top-1">
                                                <AlertCircle className="w-3 h-3" />
                                                {errors.customer}
                                            </p>
                                        )}
                                    </div>
                                </div>
                            </div>

                            {/* Invoice Metadata - Right Section */}
                            {/* Invoice Metadata - Right Section */}
                            <div className="col-span-12 lg:col-span-5 space-y-6">
                                {/* Invoice Number */}
                                <div className="space-y-1.5 group">
                                    <label className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wider ml-1">
                                        Invoice Number
                                    </label>
                                    <div className="relative">
                                        <Hash className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 group-focus-within:text-primary-500 transition-colors" />
                                        <input
                                            type="text"
                                            name="invoiceNumber"
                                            value={formData.invoiceNumber}
                                            readOnly={true}
                                            className={`${getInputClass('invoiceNumber')} font-mono bg-gray-100 dark:bg-slate-800 text-gray-500 cursor-not-allowed`}
                                            placeholder="Auto-generated on save"
                                        />
                                    </div>
                                </div>

                                {/* Dates Row */}
                                <div className="grid grid-cols-2 gap-4">
                                    <div className="space-y-1.5 group">
                                        <label className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wider ml-1">
                                            Issue Date
                                        </label>
                                        <div className="relative">
                                            <Calendar className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 group-focus-within:text-primary-500 transition-colors" />
                                            <input
                                                type="date"
                                                name="invoiceDate"
                                                value={formData.invoiceDate}
                                                onChange={handleChange}
                                                onBlur={() => handleBlur('invoiceDate')}
                                                required
                                                className={getInputClass('invoiceDate')}
                                            />
                                        </div>
                                        {touched.invoiceDate && errors.invoiceDate && (
                                            <p className="text-xs text-red-600 dark:text-red-400 ml-1">{errors.invoiceDate}</p>
                                        )}
                                    </div>

                                    <div className="space-y-1.5 group">
                                        <label className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wider ml-1">
                                            Due Date
                                        </label>
                                        <div className="relative">
                                            <Clock className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 group-focus-within:text-primary-500 transition-colors" />
                                            <input
                                                type="date"
                                                name="dueDate"
                                                value={formData.dueDate}
                                                onChange={handleChange}
                                                onBlur={() => handleBlur('dueDate')}
                                                min={formData.invoiceDate}
                                                required
                                                className={getInputClass('dueDate')}
                                            />
                                        </div>
                                        {touched.dueDate && errors.dueDate && (
                                            <p className="text-xs text-red-600 dark:text-red-400 ml-1">{errors.dueDate}</p>
                                        )}
                                    </div>
                                </div>

                            </div>
                        </div>

                        {/* Items Section - Professional Table */}
                        <div className="mb-8">
                            <div className="flex items-center justify-between mb-4">
                                <h2 className="text-lg font-semibold text-gray-900 dark:text-slate-100 flex items-center gap-2">
                                    <Box className="w-5 h-5 text-primary-500" />
                                    Items & Services
                                </h2>
                                <button
                                    type="button"
                                    onClick={addItem}
                                    className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-primary-600 hover:bg-primary-700 rounded-xl shadow-lg shadow-primary-500/20 transition-all active:scale-95"
                                >
                                    <Plus className="w-4 h-4" />
                                    Add Line Item
                                </button>
                            </div>

                            {errors.items && (
                                <div className="mb-4 p-3 bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-900/50 rounded-lg flex items-center gap-2 text-sm text-red-700 dark:text-red-400 animate-in slide-in-from-top-2">
                                    <AlertCircle className="w-4 h-4" />
                                    {errors.items}
                                </div>
                            )}

                            {/* Responsive Table */}
                            <div className="bg-white dark:bg-slate-900 rounded-2xl border border-gray-200 dark:border-slate-700 overflow-hidden shadow-sm">
                                <div className="overflow-x-auto">
                                    <table className="w-full min-w-[900px]">
                                        <thead className="bg-gray-50/80 dark:bg-slate-800/50 border-b border-gray-100 dark:border-slate-700/50">
                                            <tr>
                                                <th className="px-6 py-4 text-left text-xs font-bold text-gray-500 dark:text-slate-400 uppercase tracking-wider">Item Details</th>
                                                <th className="px-6 py-4 text-right text-xs font-bold text-gray-500 dark:text-slate-400 uppercase tracking-wider w-32">Qty</th>
                                                <th className="px-6 py-4 text-right text-xs font-bold text-gray-500 dark:text-slate-400 uppercase tracking-wider w-40">Price</th>
                                                <th className="px-6 py-4 text-right text-xs font-bold text-gray-500 dark:text-slate-400 uppercase tracking-wider w-32">
                                                    <div className="flex items-center justify-end gap-1.5">
                                                        <span>Tax %</span>
                                                        <div className="group/tooltip relative inline-block">
                                                            <HelpCircle className="w-3 h-3 text-gray-400 cursor-help" />
                                                            <div className="invisible group-hover/tooltip:visible absolute right-0 top-5 z-10 w-48 p-2 bg-gray-900 dark:bg-slate-800 text-white text-[10px] rounded-lg shadow-lg whitespace-normal">
                                                                Tax rate (%) applied to item price. Final amount = Price × Qty × (1 + Tax/100)
                                                            </div>
                                                        </div>
                                                    </div>
                                                </th>
                                                <th className="px-6 py-4 text-right text-xs font-bold text-gray-500 dark:text-slate-400 uppercase tracking-wider w-40">Amount</th>
                                                <th className="px-6 py-4 w-16"></th>
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-gray-100 dark:divide-slate-800">
                                            {formData.items.map((item, index) => {
                                                const lineTotal = (item.quantity * item.price) * (1 + item.taxRate / 100)
                                                const hasError = errors[`item_${index}_quantity`]

                                                return (
                                                    <tr key={index} className="group hover:bg-gray-50/50 dark:hover:bg-slate-800/30 transition-colors">
                                                        <td className="px-6 py-4 align-top">
                                                            <ItemSelect
                                                                value={item.itemId}
                                                                onChange={(id) => handleItemSelect(index, id)}
                                                                items={items}
                                                            />
                                                        </td>
                                                        <td className="px-6 py-4 align-top">
                                                            <input
                                                                type="number"
                                                                min="1"
                                                                value={item.quantity}
                                                                onChange={(e) => handleItemChange(index, 'quantity', parseFloat(e.target.value) || 0)}
                                                                onBlur={() => setTouched(prev => ({ ...prev, [`item_${index}_quantity`]: true }))}
                                                                className={`w-full text-right px-3 py-2.5 bg-white dark:bg-slate-900 border ${touched[`item_${index}_quantity`] && hasError ? 'border-red-300 focus:border-red-500 ring-2 ring-red-500/10' : 'border-gray-200 dark:border-slate-700 focus:border-primary-500'} rounded-xl text-sm outline-none focus:ring-2 focus:ring-primary-500/10 transition-all`}
                                                            />
                                                            {touched[`item_${index}_quantity`] && hasError && (
                                                                <p className="text-[10px] text-red-600 dark:text-red-400 mt-1 text-right">{hasError}</p>
                                                            )}
                                                        </td>
                                                        <td className="px-6 py-4 align-top">
                                                            <div className="relative">
                                                                <DollarSign className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" />
                                                                <input
                                                                    type="number"
                                                                    min="0"
                                                                    step="0.01"
                                                                    value={item.price}
                                                                    onChange={(e) => handleItemChange(index, 'price', parseFloat(e.target.value) || 0)}
                                                                    className="w-full text-right pl-8 pr-3 py-2.5 bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700 rounded-xl text-sm outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/10 transition-all"
                                                                />
                                                            </div>
                                                        </td>
                                                        <td className="px-6 py-4 align-top">
                                                            <div className="relative">
                                                                <input
                                                                    type="number"
                                                                    min="0"
                                                                    step="0.1"
                                                                    value={item.taxRate}
                                                                    onChange={(e) => handleItemChange(index, 'taxRate', parseFloat(e.target.value) || 0)}
                                                                    className="w-full text-right pr-8 pl-3 py-2.5 bg-white dark:bg-slate-900 border border-gray-200 dark:border-slate-700 rounded-xl text-sm outline-none focus:border-primary-500 focus:ring-2 focus:ring-primary-500/10 transition-all"
                                                                />
                                                                <Percent className="absolute right-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400" />
                                                            </div>
                                                        </td>
                                                        <td className="px-6 py-4 align-top text-right pt-5">
                                                            <span className="font-semibold text-gray-900 dark:text-slate-100">
                                                                ${lineTotal.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                                                            </span>
                                                        </td>
                                                        <td className="px-6 py-4 align-top pt-3.5">
                                                            {formData.items.length > 1 && (
                                                                <button
                                                                    type="button"
                                                                    onClick={() => removeItem(index)}
                                                                    className="p-2 text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded-lg transition-all opacity-0 group-hover:opacity-100"
                                                                >
                                                                    <Trash2 className="w-4 h-4" />
                                                                </button>
                                                            )}
                                                        </td>
                                                    </tr>
                                                )
                                            })}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>

                        {/* Bottom Grid: Notes + Totals */}
                        <div className="grid grid-cols-12 gap-8">
                            {/* Notes Section */}
                            <div className="col-span-12 lg:col-span-7 space-y-3">
                                <label className="text-xs font-semibold text-gray-500 dark:text-slate-400 uppercase tracking-wider ml-1">
                                    Notes & Terms
                                </label>
                                <div className="relative">
                                    <FileText className="absolute left-3.5 top-3.5 w-4 h-4 text-gray-400" />
                                    <textarea
                                        name="notes"
                                        rows="4"
                                        value={formData.notes}
                                        onChange={handleChange}
                                        placeholder="Add any additional notes, payment terms, or special instructions..."
                                        className={`${getInputClass('notes')} pl-10 resize-none`}
                                    />
                                </div>
                            </div>

                            {/* Professional Totals Card */}
                            <div className="col-span-12 lg:col-span-5">
                                <div className="bg-white dark:bg-slate-900 rounded-2xl border border-gray-100 dark:border-slate-800 p-6 shadow-sm">
                                    <h3 className="text-xs font-semibold text-gray-500 dark:text-slate-400 mb-6 uppercase tracking-wider">
                                        Summary
                                    </h3>
                                    <div className="space-y-4">
                                        <div className="flex justify-between text-sm">
                                            <span className="text-gray-600 dark:text-slate-400">Subtotal</span>
                                            <span className="font-medium text-gray-900 dark:text-slate-100">
                                                ${totals.subtotal.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                                            </span>
                                        </div>
                                        <div className="flex justify-between text-sm">
                                            <span className="text-gray-600 dark:text-slate-400">Tax Total</span>
                                            <span className="font-medium text-gray-900 dark:text-slate-100">
                                                ${totals.taxAmount.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                                            </span>
                                        </div>
                                        <div className="pt-4 mt-2 border-t border-dashed border-gray-200 dark:border-slate-700">
                                            <div className="flex justify-between items-center">
                                                <span className="text-lg font-bold text-gray-900 dark:text-slate-100">Total Due</span>
                                                <div className="text-right">
                                                    <div className="text-2xl font-bold text-primary-600 dark:text-primary-400">
                                                        ${totals.total.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {/* Professional Sticky Footer */}
                <div className="sticky bottom-0 z-20 bg-white/95 dark:bg-slate-900/95 backdrop-blur-lg border-t border-gray-200 dark:border-slate-800 shadow-2xl">
                    <div className="max-w-7xl mx-auto px-8 py-4">
                        <div className="flex items-center justify-between">
                            <Link
                                to={backUrl}
                                className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-600 dark:text-slate-400 hover:text-gray-900 dark:hover:text-slate-200 transition-colors"
                            >
                                <X className="w-4 h-4" />
                                Cancel
                            </Link>

                            <div className="flex items-center gap-4">
                                <div className="text-right mr-4">
                                    <div className="text-xs text-gray-500 dark:text-slate-400">Total Amount</div>
                                    <div className="text-lg font-bold text-gray-900 dark:text-slate-100">
                                        ${totals.total.toLocaleString(undefined, { minimumFractionDigits: 2 })}
                                    </div>
                                </div>

                                {/* Save as Draft Button */}
                                <button
                                    type="button"
                                    onClick={(e) => handleSubmit(e, 'draft')}
                                    disabled={isSaving}
                                    className="flex items-center gap-2 px-6 py-3 bg-white dark:bg-slate-800 text-gray-700 dark:text-slate-200 font-semibold rounded-xl border border-gray-200 dark:border-slate-700 hover:bg-gray-50 dark:hover:bg-slate-700 transition-all disabled:opacity-60 disabled:cursor-not-allowed"
                                >
                                    <FileText className="w-4 h-4 text-gray-400" />
                                    Save as Draft
                                </button>

                                {/* Save and Send Button */}
                                <button
                                    type="button"
                                    onClick={(e) => handleSubmit(e, 'sent')}
                                    disabled={isSaving}
                                    className="flex items-center gap-2 px-6 py-3 bg-emerald-600 hover:bg-emerald-700 text-white font-semibold rounded-xl shadow-lg shadow-emerald-500/30 hover:shadow-emerald-500/40 transition-all disabled:opacity-60 disabled:cursor-not-allowed transform active:scale-95"
                                >
                                    {isSaving ? (
                                        <>
                                            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                                            Processing...
                                        </>
                                    ) : (
                                        <>
                                            <CheckCircle2 className="w-4 h-4" />
                                            Save and Send
                                        </>
                                    )}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>

            {/* Duplicate Warning Modal */}
            <DuplicateWarningModal
                isOpen={showDuplicateWarning}
                onClose={handleCancelDuplicate}
                onProceed={handleProceedWithDuplicate}
                duplicates={duplicateInvoices}
            />
        </>
    )
}

export default InvoiceForm
